from .models import DamageReport
from django.db import transaction


DATA = [
    {
        "first_name": "Hans",
        "last_name": "Müller",
        "accident_date": "2024-11-15",
        "address": "Hauptstraße 10, 90403 Nürnberg",
        "email": "hans.mueller@example.com",
        "phone_number": "0911-1234567",
        "bank_name": "Sparkasse Nürnberg",
        "iban": "DE89370400440532013000",
        "bic": "COBADEFFXXX",
        "bank_holder": "Hans Müller",
        "plate_number": "N-AB 123",
        "inspection": "2026-05-20",
        "opponent_plate_number": "ERH-CD 456",
        "opponent_insurance_number": "GH789012345",
        "damage_number": "KS987654321-0004",
        "witnesses": True,
        "accident_datetime": "2024-11-15T10:30:00",
        "accident_location": "Kreuzung Hauptstraße / Bahnhofstraße, Nürnberg",
        "accident_scenario": "Herr Müller fuhr auf der Hauptstraße in Richtung Osten. An der Kreuzung zur Bahnhofstraße zeigte die Ampel Rot. Er bremste sein Fahrzeug ordnungsgemäß ab. Der Unfallgegner bemerkte die rote Ampel offenbar zu spät und fuhr ungebremst auf das Heck von Herrn Müllers Fahrzeug auf. Es entstand Sachschaden an beiden Fahrzeugen."
    },
    {
        "first_name": "Anna",
        "last_name": "Schmidt",
        "accident_date": "2025-01-20",
        "address": "Goethestraße 5, 90482 Nürnberg",
        "email": "anna.schmidt@muster.de",
        "phone_number": "0911-9876543",
        "bank_name": "Deutsche Bank",
        "iban": "DE12300700100123456789",
        "bic": "DEUTDEDBXXX",
        "bank_holder": "Anna Schmidt",
        "plate_number": "FÜ-EF 789",
        "inspection": "2027-02-10",
        "opponent_plate_number": "N-GH 012",
        "opponent_insurance_number": "IJ012345678",
        "damage_number": "KS123456789-0004",
        "witnesses": False,
        "accident_datetime": "2025-01-20T14:45:00",
        "accident_location": "Parkplatz Supermarkt, Äußere Sulzbacher Straße, Nürnberg",
        "accident_scenario": "Frau Schmidt parkte rückwärts aus einer Parklücke auf dem Supermarktparkplatz. Gleichzeitig fuhr der Unfallgegner mit seinem Fahrzeug auf der Fahrgasse entlang. Frau Schmidt übersah das herannahende Fahrzeug und stieß mit dessen Seite zusammen. Beide Fahrzeuge wurden leicht beschädigt. Es gab keine Verletzten."
    },
    {
        "first_name": "Peter",
        "last_name": "Wagner",
        "accident_date": "2024-09-05",
        "address": "Königsstraße 22, 90402 Nürnberg",
        "email": "peter.wagner@online.com",
        "phone_number": "0176-11223344",
        "bank_name": "Commerzbank",
        "iban": "DE45500105176789012345",
        "bic": "COBADEFFXXX",
        "bank_holder": "Peter Wagner",
        "plate_number": "N-IJ 567",
        "inspection": "2025-11-30",
        "opponent_plate_number": "SC-KL 890",
        "opponent_insurance_number": "MN345678901",
        "damage_number": "KS098765432-0004",
        "witnesses": True,
        "accident_datetime": "2024-09-05T08:15:00",
        "accident_location": "Einmündung Bayreuther Straße / Rathenauplatz, Nürnberg",
        "accident_scenario": "Herr Wagner befuhr die Bayreuther Straße und wollte an der Einmündung zum Rathenauplatz nach links abbiegen. Dabei übersah er das entgegenkommende Fahrzeug des Unfallgegners, der auf dem Rathenauplatz in Richtung Innenstadt unterwegs war. Es kam zum Zusammenstoß im Einmündungsbereich. Zeugen bestätigten, dass Herr Wagner die Vorfahrt missachtet hatte."
    },
    {
        "first_name": "Julia",
        "last_name": "Becker",
        "accident_date": "2025-03-10",
        "address": "Theresienstraße 8, 90461 Nürnberg",
        "email": "julia.becker@mail.de",
        "phone_number": "0911-5566778",
        "bank_name": "HypoVereinsbank",
        "iban": "DE78700202700012345678",
        "bic": "HYVEDEMM408",
        "bank_holder": "Julia Becker",
        "plate_number": "ER-MN 234",
        "inspection": "2026-08-15",
        "opponent_plate_number": "N-OP 345",
        "opponent_insurance_number": "PQ678901234",
        "damage_number": "KS234567890-0004",
        "witnesses": False,
        "accident_datetime": "2025-03-10T16:00:00",
        "accident_location": "In der Tiefgarage eines Einkaufszentrums, Nürnberg",
        "accident_scenario": "Frau Becker fuhr mit ihrem Fahrzeug in einer der Fahrgassen der Tiefgarage. Der Unfallgegner wollte aus einer Parklücke ausparken. Aufgrund mangelnder Übersicht kam es zum seitlichen Zusammenstoß der beiden Fahrzeuge. Beide Parteien waren sich zunächst uneinig über die Schuldfrage, da die Sichtverhältnisse eingeschränkt waren."
    },
    {
        "first_name": "Michael",
        "last_name": "Weber",
        "accident_date": "2024-12-28",
        "address": "Breite Gasse 15, 90402 Nürnberg",
        "email": "michael.weber@gmx.net",
        "phone_number": "0151-98765432",
        "bank_name": "Postbank",
        "iban": "DE51100100100123456789",
        "bic": "PBNKDEFFXXX",
        "bank_holder": "Michael Weber",
        "plate_number": "LAU-QR 678",
        "inspection": "2027-01-05",
        "opponent_plate_number": "N-RS 678",
        "opponent_insurance_number": "ST901234567",
        "damage_number": "KS345678901-0004",
        "witnesses": True,
        "accident_datetime": "2024-12-28T11:30:00",
        "accident_location": "Auf der A73 in Richtung Fürth, Höhe Nürnberg-Zentrum",
        "accident_scenario": "Herr Weber befuhr die mittlere Spur der A73 in Richtung Fürth. Der Unfallgegner wechselte von der rechten auf die mittlere Spur, ohne auf den nachfolgenden Verkehr zu achten. Es kam zum seitlichen Zusammenstoß der beiden Fahrzeuge. Herr Weber konnte den Unfall trotz einer Notbremsung nicht mehr verhindern. Ein weiterer Verkehrsteilnehmer bestätigte den Unfallhergang."
    },
    {
        "first_name": "Sabine",
        "last_name": "Fischer",
        "accident_date": "2025-02-18",
        "address": "Lange Zeile 3, 90419 Nürnberg",
        "email": "sabine.fischer@web.de",
        "phone_number": "0911-8899001",
        "bank_name": "Norisbank",
        "iban": "DE64100777000123456789",
        "bic": "NORSDE51XXX",
        "bank_holder": "Sabine Fischer",
        "plate_number": "RH-TU 901",
        "inspection": "2026-07-25",
        "opponent_plate_number": "AN-VW 234",
        "opponent_insurance_number": "UV234567890",
        "damage_number": "KS456789012-0004",
        "witnesses": False,
        "accident_datetime": "2025-02-18T09:45:00",
        "accident_location": "Fußgängerzone Karolinenstraße, Nürnberg",
        "accident_scenario": "Frau Fischer ging zu Fuß in der Karolinenstraße. Ein Fahrradfahrer kam entgegen und klingelte, um auf sich aufmerksam zu machen. Frau Fischer wich zur Seite aus und stieß dabei unglücklich gegen einen parkenden Roller. Sie stürzte und zog sich leichte Verletzungen zu. Der Fahrradfahrer setzte seine Fahrt fort, ohne anzuhalten."
    },
    {
        "first_name": "Thomas",
        "last_name": "Braun",
        "accident_date": "2024-10-01",
        "address": "Bucher Straße 45, 90419 Nürnberg",
        "email": "thomas.braun@t-online.de",
        "phone_number": "0171-22334455",
        "bank_name": "Targobank",
        "iban": "DE27300209000123456789",
        "bic": "CMCIDEDDXXX",
        "bank_holder": "Thomas Braun",
        "plate_number": "BA-WX 345",
        "inspection": "2025-12-10",
        "opponent_plate_number": "N-YZ 789",
        "opponent_insurance_number": "WX456789012",
        "damage_number": "KS567890123-0004",
        "witnesses": True,
        "accident_datetime": "2024-10-01T13:15:00",
        "accident_location": "Baustelle in der Fürther Straße, Nürnberg",
        "accident_scenario": "Herr Braun befuhr die Fürther Straße, wo aufgrund einer Baustelle eine Fahrspur verengt war. Ein LKW des Unfallgegners kam ihm entgegen. Plötzlich löste sich ein ungesichertes Bauteil von der Ladefläche des LKW und fiel auf die Fahrbahn. Herr Braun konnte nicht mehr rechtzeitig bremsen und überfuhr das Teil, wodurch sein Fahrzeug beschädigt wurde. Zeugen bestätigten die mangelhafte Ladungssicherung."
    },
    {
        "first_name": "Sandra",
        "last_name": "Schwarz",
        "accident_date": "2025-03-05",
        "address": "Gibitzenhofstraße 12, 90443 Nürnberg",
        "email": "sandra.schwarz@gmail.com",
        "phone_number": "0911-6677889",
        "bank_name": "DKB",
        "iban": "DE88120300001234567890",
        "bic": "BYLADEM1001",
        "bank_holder": "Sandra Schwarz",
        "plate_number": "FO-ZA 456",
        "inspection": "2026-09-20",
        "opponent_plate_number": "EBE-AB 567",
        "opponent_insurance_number": "YZ567890123",
        "damage_number": "KS678901234-0004",
        "witnesses": False,
        "accident_datetime": "2025-03-05T17:30:00",
        "accident_location": "Am Plärrer, Nürnberg",
        "accident_scenario": "Frau Schwarz fuhr auf dem Plärrer und wollte nach links in eine Seitenstraße abbiegen. Der Unfallgegner kam ihr auf der Hauptstraße entgegen und wollte geradeaus weiterfahren. Es kam zum Zusammenstoß im Kreuzungsbereich, da beide Parteien möglicherweise die Vorfahrtsregeln falsch interpretiert haben. Die Ampelanlage war zu diesem Zeitpunkt außer Betrieb."
    },
    {
        "first_name": "Andreas",
        "last_name": "Meier",
        "accident_date": "2024-11-22",
        "address": "Südliche Stadtmauerstraße 7, 90403 Nürnberg",
        "email": "andreas.meier@outlook.de",
        "phone_number": "0160-33445566",
        "bank_name": "ING",
        "iban": "DE91500105170123456789",
        "bic": "INGDDEFFXXX",
        "bank_holder": "Andreas Meier",
        "plate_number": "HIP-BC 789",
        "inspection": "2027-03-15",
        "opponent_plate_number": "N-DE 890",
        "opponent_insurance_number": "ZA678901234",
        "damage_number": "KS789012345-0004",
        "witnesses": True,
        "accident_datetime": "2024-11-22T14:00:00",
        "accident_location": "Kreisverkehr am Wöhrder See, Nürnberg",
        "accident_scenario": "Herr Meier befuhr den Kreisverkehr am Wöhrder See und setzte den Blinker, um die nächste Ausfahrt zu nehmen. Der Unfallgegner fuhr in den Kreisverkehr ein, ohne die Vorfahrt zu beachten und kollidierte mit dem Fahrzeug von Herrn Meier. Zeugen bestätigten, dass der Unfallgegner die Vorfahrt im Kreisverkehr missachtet hatte und es dadurch zum Zusammenstoß kam."
    },
    {
        "first_name": "Martina",
        "last_name": "Wolf",
        "accident_date": "2025-01-10",
        "address": "Obere Schmiedgasse 19, 90402 Nürnberg",
        "email": "martina.wolf@freenet.de",
        "phone_number": "0911-4455667",
        "bank_name": "Santander Bank",
        "iban": "DE04500333000123456789",
        "bic": "SANTDEDEXXX",
        "bank_holder": "Martina Wolf",
        "plate_number": "CO-EF 012",
        "inspection": "2026-06-01",
        "opponent_plate_number": "ERH-FG 345",
        "opponent_insurance_number": "AB890123456",
        "damage_number": "KS890123456-0004",
        "witnesses": False,
        "accident_datetime": "2025-01-10T18:45:00",
        "accident_location": "Am Hauptbahnhof, Nürnberg",
        "accident_scenario": "Frau Wolf parkte ihr Fahrzeug am Straßenrand in der Nähe des Hauptbahnhofs. Nachdem sie den Motor abgestellt hatte, öffnete sie die Fahrertür, um auszusteigen. Dabei übersah sie das herannahende Fahrzeug des Unfallgegners, der gerade vorbeifahren wollte. Die geöffnete Tür kollidierte mit der Seite des anderen Fahrzeugs und verursachte einen Lackschaden."
    }
]


def save_data(workshop):
    with transaction.atomic():  # Starte Transaktion
        reports_to_create = []

        for data in DATA:

            # Erstelle Objektinstanz ohne DB-Operation
            report = DamageReport(
                workshop=workshop,
                first_name=data["first_name"],
                last_name=data["last_name"],
                accident_date=data["accident_date"],
                address=data["address"],
                email=data["email"],
                phone_number=data["phone_number"],
                bank_name=data["bank_name"],
                iban=data["iban"],
                bic=data["bic"],
                bank_holder=data["bank_holder"],
                plate_number=data["plate_number"],
                inspection=data["inspection"],
                opponent_plate_number=data["opponent_plate_number"],
                opponent_insurance_number=data["opponent_insurance_number"],
                damage_number=data["damage_number"],
                witnesses=data["witnesses"],
                accident_datetime=data["accident_datetime"],
                accident_location=data["accident_location"],
                accident_scenario=data["accident_scenario"],
                person_or_company="private"
            )

            # Vollständige Validierung

            report.full_clean()
            reports_to_create.append(report)

        # Masseninsert wenn alle validiert sind
        DamageReport.objects.bulk_create(reports_to_create)
