# Generated by Django 4.2.19 on 2025-03-05 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopData',
            fields=[
                ('workshop_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Werkstatt Name')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Addresse')),
                ('plz', models.CharField(blank=True, max_length=7, null=True, verbose_name='Postleitzahl')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Stadt')),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Land')),
                ('primary_contact', models.CharField(blank=True, help_text='Schlüsselfigur für persönliche Kontakte und Anfragen.', max_length=150, null=True, verbose_name='Ansprechpartner')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefonnummer')),
                ('email', models.CharField(blank=True, help_text='E-Mail-Adresse für digitale Kommunikation', max_length=250, null=True, verbose_name='E-Mail-Adresse')),
                ('tax_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='USt-IdNr.')),
                ('verification_document', models.FileField(blank=True, help_text='Z.B. Gewerbeschein, um die Echtheit zu prüfen', null=True, upload_to='workshop_verifications/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
