# Generated by Django 4.2.19 on 2025-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workshopdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshopdata',
            options={'ordering': ['workshop_name']},
        ),
        migrations.AlterField(
            model_name='workshopdata',
            name='verification_document',
            field=models.FileField(blank=True, help_text='Z.B. Gewerbeschein, um die Echtheit zu prüfen', null=True, upload_to='workshops/verification'),
        ),
    ]
