# Generated by Django 4.2.19 on 2025-03-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_workshopdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopdata',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='accounts.account'),
        ),
    ]
