# Generated by Django 4.2.19 on 2025-03-23 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_workshopdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('person_or_company', models.CharField(blank=True, choices=[('private', 'Privatperson'), ('company', 'Firma')], max_length=200, null=True, verbose_name='Privatperson/Firma')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nachname')),
                ('accident_date', models.DateField(blank=True, null=True, verbose_name='Unfalldatum')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Unterschrift')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-Mail')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefonnummer')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bankname')),
                ('iban', models.CharField(blank=True, max_length=25, null=True, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=25, null=True, verbose_name='BIC')),
                ('bank_holder', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kontoinhaber')),
                ('legal_protection', models.BooleanField(blank=True, default=False, verbose_name='Rechtschutz vorhanden')),
                ('plate_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Kennzeichen')),
                ('inspection', models.DateField(blank=True, null=True, verbose_name='HU')),
                ('checkbook_exists', models.BooleanField(blank=True, default=False, verbose_name='Scheckheft vorhanden')),
                ('checkbook', models.FileField(blank=True, help_text='Schekheft Upload', null=True, upload_to='reports/checkbooks')),
                ('leased', models.BooleanField(blank=True, default=False, verbose_name='Geleast')),
                ('financed', models.BooleanField(blank=True, default=False, verbose_name='Finanziert')),
                ('opponent_plate_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Kennzeichen (Unfallgegner)')),
                ('opponent_insurance_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vers.-Nr. (Unfallgegner)')),
                ('damage_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Schadensnummer')),
                ('witnesses', models.BooleanField(blank=True, default=False, verbose_name='Zeugen')),
                ('accident_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Unfalldatum & -uhrzeit')),
                ('accident_location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Unfallort')),
                ('accident_scenario', models.TextField(blank=True, null=True, verbose_name='Unfallort')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounts.account')),
            ],
            options={
                'ordering': ['accident_date', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='DamageImage',
            fields=[
                ('image', models.ImageField(upload_to='damage_reports/%Y/%m/%d/', verbose_name='Bild')),
                ('image_view', models.CharField(choices=[('front_left', 'Ansicht vorne links'), ('front_right', 'Ansicht vorne rechts'), ('rear_left', 'Ansicht hinten links'), ('rear_right', 'Ansicht hinten rechts'), ('other', 'Sonstiges')], default='other', max_length=30, verbose_name='Bildansicht')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('damage_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.damagereport', verbose_name='Schadensbericht')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
