# Generated by Django 4.2.19 on 2025-03-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_workshopdata_account'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='account',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Werkstatt', to='accounts.workshopdata'),
        ),
    ]
