# Generated by Django 4.2.19 on 2025-04-08 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_workshopdata_account'),
        ('reports', '0002_remove_damagereport_account_damagereport_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentScenarioOption',
            fields=[
                ('scenario', models.CharField(max_length=255, unique=True, verbose_name='Unfallhergang')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='accident_scenario',
            field=models.TextField(blank=True, null=True, verbose_name='Unfallhergang'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.workshopdata'),
        ),
    ]
