# Generated by Django 4.2.19 on 2025-04-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_accidentscenariooption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damagereport',
            old_name='accident_scenario',
            new_name='accident_notes',
        ),
    ]
