# Generated by Django 4.2.19 on 2025-04-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_accident_scenario_damagereport_accident_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='accident_scenarios',
            field=models.ManyToManyField(blank=True, related_name='damage_reports', to='reports.accidentscenariooption', verbose_name='unfallszenarien (Mehrfachauswahl möglich)'),
        ),
    ]
