# Generated by Django 4.2.19 on 2025-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_damagereport_accident_scenarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='bank_holder',
        ),
        migrations.RemoveField(
            model_name='damagereport',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='damagereport',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='damagereport',
            name='legal_protection',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='bank_image',
            field=models.ImageField(blank=True, null=True, upload_to='bank_info_images/', verbose_name='Foto der Bankkarte'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Firmenname'),
        ),
    ]
