# Generated by Django 4.2.19 on 2025-04-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_damagereport_bank_holder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagereport',
            options={'ordering': ['created', 'first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='damagereport',
            name='accident_date',
        ),
    ]
