# Generated by Django 4.2.19 on 2025-04-16 13:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_damagereport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='witnesses',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='has_witnesses',
            field=models.BooleanField(blank=True, default=False, verbose_name='Gibt es Zeugen?'),
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefonnummer')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('damage_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='reports.damagereport', verbose_name='Zugehöriger Schadensbericht')),
            ],
            options={
                'ordering': ['damage_report', 'created'],
            },
        ),
    ]
