# Generated by Django 4.2.19 on 2025-04-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_damagereport_witnesses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='witness_textfield',
            field=models.TextField(blank=True, null=True),
        ),
    ]
