# Generated by Django 5.2.1 on 2025-07-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_rename_last_name_witness_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='autoixpert_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autoixpert ID'),
        ),
        migrations.AlterField(
            model_name='witness',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
