# Generated by Django 5.2.1 on 2025-07-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_damagereport_autoixpert_id_alter_witness_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='inspection',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='HU (MM/YYYY)'),
        ),
    ]
