# Generated by Django 5.2.1 on 2025-07-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_damagereport_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageimage',
            name='autoixpert_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autoixpert ID'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='inspection',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='HU (MM/YYYY)'),
        ),
    ]
